### ISSUE TITLE
Add Windows unzipping

### ISSUE THREAD

**Issue by vladikoff** [vladikoff/node-geckodriver#5]
need to use unzip otherwise:

![](http://v14d.com/i/57a4f90de9486.png)

**Comment by aberonni** [comment]
Just got this error too.

**Comment by Ivan-Katovich** [comment]
The same issue.

**Comment by elwitoldo** [comment]
Hi, I have the same issue. The problem is that windows package is plain zip:

var DOWNLOAD_MAC = 'https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-macos.tar.gz'
var DOWNLOAD_LINUX = 'https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-linux64.tar.gz'
var DOWNLOAD_WIN = 'https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-win64.zip'

when compared to MAC and LINUX which are .gz files.

Solution is to replace this code:

targz().extract(path.join(__dirname, outFile), __dirname)

and add condition, i.e.:

``
if (platform === 'win32') {
	var archive = path.join(__dirname, outFile);
	var target_dir = __dirname;
	got.stream(downloadUrl)
	  .pipe(fs.createWriteStream(outFile))
	  .on('close', function() {
		process.stdout.write('Extracting... ');
		extract(archive, {dir: target_dir}, function (err) {
			if(err) {
				console.log('Something is wrong ', err.stack);
				return;
				}
			else {
				console.log('Complete.');
			}
		})
	});		
}
``

**Comment by vladikoff** [comment]
Fixed via https://github.com/vladikoff/node-geckodriver/commit/7cacd8e651be3ba4d5b7cf340b62a808bd7e3a68
